import { allDiagnostics, moveProgram, removeProgram, setProgramInTimeline, type ProgramRef } from '@sponcam/core';
import { Loader2, MoreHorizontal } from 'lucide-react';
import type React from 'react';
import type { ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { activateProgram } from '@/gcode/playback';
import { cn } from '@/lib/utils';
import { allPrograms } from '@/state/programList';
import { pruneBlobs } from '@/state/programs';
import { appStore, useApp } from '@/state/store';
import { formatDuration } from './format';

function removeImported(id: string): void {
  appStore.getState().commit((j) => removeProgram(j, id));
  const s = appStore.getState();
  if (s.activeProgramId === id) s.setActiveProgram(allPrograms(s)[0]?.id ?? null);
  void pruneBlobs();
}

export function ProgramRow({ p, index, count, dragHandle }: {
  p: ProgramRef; /** Position among the imported programs; only imported rows have a ⋯ menu. */ index?: number; count?: number; dragHandle?: ReactNode;
}) {
  const d = useApp((s) => s.programData[p.blobId]);
  const active = useApp((s) => s.activeProgramId === p.id);
  const { commit } = appStore.getState();
  const diags = d?.parsed ? allDiagnostics(d.parsed) : [];
  const errors = diags.filter((x) => x.severity === 'error').length;
  const warnings = diags.filter((x) => x.severity === 'warning').length;
  const generated = p.source === 'generated';
  const stop = (e: React.MouseEvent) => e.stopPropagation();

  return (
    <div
      data-testid={`program-${p.name}`} data-active={active} onClick={() => activateProgram(p.id)}
      className={cn('cursor-pointer rounded-md border px-2 py-1.5 text-sm', active ? 'border-primary bg-accent' : 'hover:bg-accent/50')}
    >
      <div className="flex items-start gap-2">
        {!generated && dragHandle}
        {generated ? (
          <span data-testid="program-generated" className="rounded bg-accent px-1 text-xs text-muted-foreground" title="Generated by the CAM pipeline">
            generated
          </span>
        ) : (
          <input
            type="checkbox" data-testid="program-in-timeline" checked={p.inTimeline} className="mt-0.5 accent-primary" title="Include in timeline"
            onClick={stop} onChange={(e) => commit((j) => setProgramInTimeline(j, p.id, e.target.checked))}
          />
        )}
        <span className="min-w-0 flex-1 break-words" title={p.name}>{p.name}</span>
        {d?.status === 'parsing' && <Loader2 className="size-3.5 animate-spin text-muted-foreground" />}
        {d?.status === 'failed' && <span className="text-xs text-destructive">failed</span>}
        {errors > 0 && <span className="rounded bg-destructive/20 px-1 text-xs text-destructive">{errors}</span>}
        {warnings > 0 && <span className="rounded bg-amber-500/20 px-1 text-xs text-amber-500">{warnings}</span>}
        {!generated && (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="icon" variant="ghost" className="size-6" data-testid="program-menu" aria-label={`Actions for ${p.name}`} onClick={stop}>
                <MoreHorizontal className="size-3.5" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" onClick={stop}>
              <DropdownMenuItem data-testid="program-up" disabled={index === 0} onSelect={() => commit((j) => moveProgram(j, p.id, -1))}>Move up</DropdownMenuItem>
              <DropdownMenuItem data-testid="program-down" disabled={index === (count ?? 0) - 1} onSelect={() => commit((j) => moveProgram(j, p.id, 1))}>Move down</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem data-testid="program-remove" variant="destructive" onSelect={() => removeImported(p.id)}>Remove</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        )}
      </div>
      {d?.parsed && (
        <div className={cn('mt-0.5 text-xs text-muted-foreground', !generated && 'pl-[2.75rem]')}>
          <span className="font-mono" data-testid="program-time">{formatDuration(d.parsed.analysis.summary.totalSeconds)}</span>
        </div>
      )}
    </div>
  );
}
