// Generates src/text/bundled/*.ts from the @fontsource WOFF files and the Hershey .jhf files. Run once; outputs are committed.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src/text/bundled');
const require = createRequire(import.meta.url);
mkdirSync(out, { recursive: true });
const HEADER = '// generated by scripts/build-fonts.mjs — do not edit\n';

const fontsource = (pkg, file) => join(dirname(require.resolve(`${pkg}/package.json`)), 'files', file);
const woffs = {
  sans: fontsource('@fontsource/inter', 'inter-latin-400-normal.woff'),
  sansBold: fontsource('@fontsource/inter', 'inter-latin-700-normal.woff'),
  serif: fontsource('@fontsource/roboto-slab', 'roboto-slab-latin-400-normal.woff'),
};
for (const [id, file] of Object.entries(woffs)) {
  writeFileSync(join(out, `${id}.ts`), `${HEADER}export default '${readFileSync(file).toString('base64')}';\n`);
}

// Same algorithm as parseJhf in src/text/hershey.ts (the tested copy; a test compares the two).
function parseJhf(text) {
  const R = 'R'.charCodeAt(0);
  const START = /^[ \d]{5}[ \d]{3}/;
  const lines = text.split('\n').map((l) => l.replace(/\r$/, ''));
  const glyphs = {};
  let k = 0;
  for (let i = 0; i < lines.length && k < 95; i++) {
    const head = lines[i];
    if (!START.test(head) || head.slice(0, 8).trim() === '') continue;
    const count = parseInt(head.slice(5, 8), 10);
    let data = head.slice(8);
    while (data.length < 2 * count && i + 1 < lines.length && !START.test(lines[i + 1])) data += lines[++i];
    const v = (idx) => data.charCodeAt(idx) - R;
    const strokes = [];
    let cur = [];
    for (let p = 1; p < count; p++) {
      if (data[2 * p] === ' ' && data[2 * p + 1] === 'R') {
        if (cur.length) strokes.push(cur);
        cur = [];
      } else cur.push([v(2 * p), v(2 * p + 1)]);
    }
    if (cur.length) strokes.push(cur);
    glyphs[String.fromCharCode(32 + k)] = { left: v(0), right: v(1), strokes };
    k++;
  }
  return { glyphs };
}
const hershey = { hersheySans: 'rowmans', hersheyDuplex: 'rowmand', hersheyScript: 'scripts' };
for (const [id, file] of Object.entries(hershey)) {
  const table = parseJhf(readFileSync(join(root, 'assets/hershey', `${file}.jhf`), 'utf8'));
  writeFileSync(join(out, `${id}.ts`), `${HEADER}import type { HersheyTable } from '../hershey';\n\nexport default ${JSON.stringify(table)} as HersheyTable;\n`);
}
